version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: linh
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: django_apps
    ports:
      - 8081:3306
    networks:
      - django-app
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - django-app

networks:
  django-app:
    driver: bridge